#!/bin/sh
#
# /etc/rc.d/qemu-agent: start/stop qemu-ga daemon
#

SSD=/sbin/start-stop-daemon
PROG=/usr/bin/qemu-ga
PID=/var/run/qemu-ga.pid

case $1 in
start)
	$SSD --start --pidfile $PID --background --exec $PROG -- -t /var/run/qemu-ga
	;;
stop)
	$SSD --stop --retry 10 --pidfile $PID
	;;
restart)
	$0 stop
	$0 start
	;;
status)
	$SSD --status --pidfile $PID
	case $? in
	0) echo "$PROG is running with pid $(cat $PID)" ;;
	1) echo "$PROG is not running but the pid file $PID exists" ;;
	3) echo "$PROG is not running" ;;
	4) echo "Unable to determine the program status" ;;
	esac
	;;
*)
	echo "usage: $0 [start|stop|restart|status]"
	;;
esac

# End of file
