#!/bin/sh
#
# /etc/rc.d/dhcpcd: start/stop dhcp client
#

SSD=/sbin/start-stop-daemon
PROG=/usr/sbin/dhclient
PID=/var/run/dhclient.pid
OPTS="-q"

case $1 in
start)
        $SSD --start --pidfile $PID --exec $PROG -- $OPTS
        ;;
stop)
        $SSD --stop --remove-pidfile --retry 10 --pidfile $PID
        ;;
restart)
        $0 stop
        $0 start
        ;;
reload)
        $SSD --stop --signal HUP --pidfile $PID
        ;;
status)
        $SSD --status --pidfile $PID
        case $? in
        0) echo "$PROG is running" ;;
        1) echo "$PROG is not running but the pid file $PID exists" ;;
        3) echo "$PROG is not running" ;;
        4) echo "Unable to determine the program status" ;;
        esac
        ;;
*)
        echo "usage: $0 [start|stop|restart|reload|status]"
        ;;
esac

# End of file

