#!/bin/sh
#
# /etc/rc.d/ngircd: start/stop the ngircd daemon
#

SSD=/sbin/start-stop-daemon
PROG=/usr/sbin/ngircd
PID=/var/run/ngircd/ngircd.pid
OPTS="-f /etc/ngircd.conf"

case $1 in
    "start")
        $SSD --start --pidfile $PID --exec $PROG -- $OPTS
        ;;
    "stop")
        $SSD --stop --retry 10 --pidfile $PID
        ;;
    "restart")
        $0 stop
        $0 start
        ;;
    "status")
        $SSD --status --pidfile $PID
        case $? in
            0)
                echo "$PROG is running with pid $(cat $PID)"
                ;;
            1)
                echo "$PROG is not running but pid file $PID exists"
                ;;
            3)
                echo "$PROG is not running"
                ;;
            4)
                echo "Unable to determine program status"
                ;;
        esac
        ;;
    *)
        echo "Usage: $0 [start|stop|restart|status]"
        ;;
esac
