#!/bin/sh
#
# /etc/rc.d/sysklogd: start/stop syslog daemon
#

SSD=/sbin/start-stop-daemon
PROG=/usr/sbin/syslogd
OPTS=-ss
PID=/var/run/syslogd.pid

case $1 in
start)
	$SSD --start --oknodo --pidfile $PID --exec $PROG  -- $OPTS
	;;
stop)
	pkill -x klogd
	$SSD --stop --retry 10 --pidfile $PID 
	;;
restart)
	$0 stop
	$0 start
	;;
status)
	$SSD --status --pidfile $PID
	case $? in
	0) echo "$PROG is running with pid $(cat $PID)" ;;
	1) echo "$PROG is not running but the pid file $PID exists" ;;
	3) echo "$PROG is not running" ;;
	4) echo "Unable to determine the program status" ;;
	esac
	;;
*)
	echo "usage: $0 [start|stop|restart|status]"
	;;
esac

# End of file
