#!/bin/sh
# pinentry wrapper

if [ -x /usr/bin/pinentry-qt5 ];then
  exec /usr/bin/pinentry-qt5 "$@"
fi

if [ -x /usr/bin/pinentry-qt ];then
  exec /usr/bin/pinentry-qt "$@"
fi

if [ -x /usr/bin/pinentry-gtk-2 ];then
  exec /usr/bin/pinentry-gtk-2 "$@"
fi

if [ -x /usr/bin/pinentry-curses ];then
  exec /usr/bin/pinentry-curses "$@"
else
  echo "no pinentry binary available" > /dev/stderr
  exit 1
fi
