#!/bin/sh
#
# /etc/rc.d/atd: start/stop at daemon
#

case $1 in
  start)
    /usr/sbin/atd
    ;;
  stop)
    killall -q /usr/sbin/atd
    ;;
  restart)
    $0 stop
    sleep 2
    $0 start
    ;;
  *)
    echo "usage: $0 [start|stop|restart]"
    ;;
esac

# End of file
