#!/bin/sh
#
# /etc/rc.d/smartd: start/stop smartd daemon
#

SSD=/sbin/start-stop-daemon
PROG=/usr/sbin/smartd
PID=/var/run/smartd.pid
OPTS="-p $PID"

case $1 in
start)
	$SSD --start --pidfile $PID --exec $PROG -- $OPTS
	;;
stop)
	$SSD --stop --retry 10 --pidfile $PID
	;;
restart)
	$0 stop
	$0 start
	;;
reload)
	$SSD --stop --pidfile $PID --signal HUP
	;;
status)
	$SSD --status --pidfile $PID
	case $? in
	0) echo "$PROG is running with pid $(cat $PID)" ;;
	1) echo "$PROG is not running but the pid file $PID exists" ;;
	3) echo "$PROG is not running" ;;
	4) echo "Unable to determine the program status" ;;
	esac
	;;
*)
	echo "usage: $0 [start|stop|restart|reload|status]"
	;;
esac

# End of file
