#!/bin/sh

if [ -z "$(getent group pulse)" ]; then
	/usr/sbin/groupadd -r pulse
fi

if [ -z "$(getent passwd pulse)" ]; then
	/usr/sbin/useradd -r -g pulse -d /var/run/pulse -s /bin/false -c "Pulseaudio System User" pulse
	/usr/bin/passwd -l pulse
fi
