#!/bin/bash
#
# /etc/rc.d/snmpd: start/stop net-snmpd daemon
#

SSD=/sbin/start-stop-daemon
PROG=/usr/sbin/snmpd
PID=/var/run/snmp/snmpd.pid
LOG=/var/log/snmp/snmpd.log
OPTS="-A -p $PID -Lf $LOG -u snmp -g snmp"

case $1 in
start)
        $SSD --start --pidfile $PID --exec $PROG -- $OPTS
        ;;
stop)
        $SSD --stop --remove-pidfile --retry 10 --pidfile $PID
        ;;
restart)
        $0 stop
        $0 start
        ;;
status)
        $SSD --status --pidfile $PID
        case $? in
        0) echo "$PROG is running with pid $(cat $PID)" ;;
        1) echo "$PROG is not running but the pid file $PID exists" ;;
        3) echo "$PROG is not running" ;;
        4) echo "Unable to determine the program status" ;;
        esac
        ;;
*)
        echo "usage: $0 [start|stop|restart|status]"
        ;;
esac

# End of file
