#!/bin/sh
#
# /etc/rc.d/hefurd: start/stop hefur daemon
#

SSD=/sbin/start-stop-daemon
PROG=/usr/bin/hefurd
PID=/var/run/hefurd.pid
OPTS="-torrent-dir /usr/share/hefur/torrents -log-file /var/log/hefurd.log"

case $1 in
start)
        $SSD --start --background --exec $PROG -- $OPTS
        ;;
stop)
        $SSD --stop --retry 10 --exec $PROG
        ;;
restart)
        $0 stop
        $0 start
        ;;
status)
        $SSD --status --exec $PROG
        case $? in
        0) echo "$PROG is running" ;;
        1) echo "$PROG is not running but the pid file $PID exists" ;;
        3) echo "$PROG is not running" ;;
        4) echo "Unable to determine the program status" ;;
        esac
        ;;
*)
        echo "usage: $0 [start|stop|restart|status]"
        ;;
esac

# End of file
