#!/bin/sh

# Created by Danny Rawlins, monster dot romster at gmail dot com

GROUP=nut
USER=nut
USER_COMMENT="Network UPS Tools"
USER_HOME=/var/empty
USER_SHELL=/bin/sh

if [ ! $(id -u) = 0 ]; then
	echo "ERROR: you need to be root to run this!"
	exit 1
fi

if [ $GROUP ];	then
	if ! getent group $GROUP > /dev/null; then
		/usr/sbin/groupadd $GROUP
		if [ $? -eq 0 ]; then
			echo "Group: $GROUP added."
		fi
	else
		echo "Group: $GROUP already exists! Skipping."
	fi
fi
	
if ! getent passwd $USER > /dev/null; then
	/usr/sbin/useradd -g $GROUP -c "$USER_COMMENT" -d $USER_HOME -s $USER_SHELL $USER
	if [ $? -eq 0 ]; then
		echo "User: $USER added."
		/usr/bin/passwd -l $USER > /dev/null
		if [ $? -eq 0 ]; then
			echo "Locked: $USER account."
		fi
		else
			echo "ERROR: unable to lock $USER account."
			/usr/sbin/userdel $USER
	fi
	else
		echo "User: $USER already exists! Skipping."
fi

