#!/bin/sh
#
# /etc/rc.d/mathopd: start/stop mathopd http daemon
#

SSD=/sbin/start-stop-daemon
PROG=/usr/sbin/mathopd
OPTS="-f /etc/mathopd.conf"

case $1 in
start)
	$SSD --start --exec $PROG -- $OPTS
	;;
stop)
	$SSD --stop --retry 10 --exec $PROG
	;;
restart)
	$0 stop
	$0 start
	;;
status)
	$SSD --status --exec $PROG
	case $? in
	0) echo "$PROG is running" ;;
	1) echo "$PROG is not running but the pid file $PID exists" ;;
	3) echo "$PROG is not running" ;;
	4) echo "Unable to determine the program status" ;;
	esac
	;;
*)
	echo "usage: $0 [start|stop|restart|status]"
	;;
esac

# End of file
