#!/bin/sh

if [ -z "`getent group nginx`" ]; then
	/usr/sbin/groupadd --system nginx
fi

if [ -z "`getent passwd nginx`" ]; then
	/usr/sbin/useradd -r -g nginx -d /etc/nginx -s /bin/false -c "nginx server" nginx
	/usr/bin/passwd -l nginx
fi
