#!/bin/sh
#
# /etc/rc.d/ntpd: start/stop ntp daemon
#

PATH="/sbin:/usr/sbin:/bin:/usr/bin"

USER="root"
RUNDIR="/var/run/openntpd"
PIDFILE="$RUNDIR/openntpd.pid"
PROG="/usr/sbin/ntpd"
ARGS="-s -p $PIDFILE"

case $1 in
start)
	install -d -m 755 -o $USER $RUNDIR || exit 1
	start-stop-daemon --start --pidfile $PIDFILE --exec $PROG -- $ARGS
	;;
stop)
	start-stop-daemon --stop --retry 60 --pidfile $PIDFILE
	;;
restart)
	$0 stop
	$0 start
	;;
status)
	start-stop-daemon --status --pidfile $PIDFILE
	case $? in
	0) echo "$PROG running with pid: $(cat $PIDFILE)" ;;
	1) echo "$PROG not running, stale pidfile: $PIDFILE" ;;
	3) echo "$PROG not running" ;;
	4) echo "Unable to determine program status" ;;
	esac
	;;
*)
	echo "usage: $0 [start|stop|restart|status]"
	;;
esac

